### ISSUE TITLE
Fe - Economy Minor Currency

### ISSUE THREAD

**Issue by samihsoylu** [niccholaspage/Fe#52]
Hello,

Within my server, My minor currency is shown within a negative balance. I was wondering if there is a way to solve this. So if I am $10 in debt I don't want to see my balance -1000 cents. This isn't right.

Here is my config: 

```
holdings: 1000
maxholdings: -1
prefix: Bank
topsize: 5
currency:
  negative: true
  major:
    single: Dollar
    multiple: Dollars
  minor:
    enabled: true
    single: Cent
    multiple: Cents
  prefix: ''
type: sqlite
updatecheck: true
mongo:
  host: localhost
  port: 27017
  user: root
  password: minecraft
  database: Fe
mysql:
  host: localhost
  port: 3306
  user: root
  password: minecraft
  database: minecraft
  tables:
    accounts: fe_accounts
item:
  item: gold_ingot
  value: 10
```

I also don't know what the gold_ingot thing is, if I could be explained how it all works, I would be grateful. Here is a quick screen shot:
![c149bb050771d4742a417c9da8ce6608](https://cloud.githubusercontent.com/assets/7690781/3075607/d3ea204c-e384-11e3-9cfa-f385c04a8042.png)

I am using Fe CB 1.7.2-R0.3 on my 1.7.9 server.

Thank you!
